# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/browsers:node12.16.2-chrome81-ff75

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run test && npm run test:e2e:ci
